import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paul's letter to the Galatians</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

<link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap, Montserrat,Roboto"
          rel="stylesheet"
        />   

            <link href="https://fonts.googleapis.com/css2?family=Rubik+Doodle+Shadow&display=swap" 
            rel="stylesheet"  
              />  
              
      </Head>
      <main className={styles.main}>
      
       <div className={styles.hero}>
           <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://thewordofgodrisen.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
       GALATIANS
        </h1>
         
         <div className={styles.iframe1}>
      <iframe width="100%" height="300" src="https://www.youtube.com/embed/KgVLE_JVhBs?si=sxT5iNn5zeNtu2GT&autoplay=1&mute=1" title="YouTube video player" frameborder="10" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                             
          </div>    


 <p className={styles.parables}> Paul writes Galatia they're being misled by the Judaizers, who demanded circumcision to be saved.</p>
                        <div className={styles.nav}>           
      <a href="https://second-corinthians.vercel.app/">
    <p>Prev</p>
             <Image 
                                src="/previous.webp"
                                alt="left"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>

         <a href="https://www.youtube.com/channel/UCC4jNk2Tms-KNO1h1YOjfRw">
  <p>Give</p>
                                  
  <Image 
                                src="/donations_please.webp"
                                alt="donations_please.webp"
                                 height={25}
                                width={25}
                                priority
                              />
          
                                  
                                  
        </a>
         <a href="https://ephesians.vercel.app/">
  <p>Next</p>
                                  
           <Image 
                                src="/next.webp"
                                alt="Jesus"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         
               </div>
   <div className={styles.iframe}>
<iframe width="100%" height="315" src="https://www.youtube.com/embed/vmx4UjRFp0M?autoplay=1&mute=1" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>  
   </div>                              
      
      <div className={styles.grid}>
          <div className={styles.card}>
            <h2  className={styles.chapter}>Galatians Chapter I</h2>
            <p>1 Paul, an apostle—sent not from men nor by a man, but by Jesus Christ and God the Father, who raised him from the dead— 2 and all the brothers and sisters[a] with me,

To the churches in Galatia:

3 Grace and peace to you from God our Father and the Lord Jesus Christ, 4 who gave himself for our sins to rescue us from the present evil age, according to the will of our God and Father, 5 to whom be glory for ever and ever. Amen.

No Other Gospel
6 I am astonished that you are so quickly deserting the one who called you to live in the grace of Christ and are turning to a different gospel— 7 which is really no gospel at all. Evidently some people are throwing you into confusion and are trying to pervert the gospel of Christ. 8 But even if we or an angel from heaven should preach a gospel other than the one we preached to you, let them be under God’s curse! 9 As we have already said, so now I say again: If anybody is preaching to you a gospel other than what you accepted, let them be under God’s curse!

10 Am I now trying to win the approval of human beings, or of God? Or am I trying to please people? If I were still trying to please people, I would not be a servant of Christ.

Paul Called by God
11 I want you to know, brothers and sisters, that the gospel I preached is not of human origin. 12 I did not receive it from any man, nor was I taught it; rather, I received it by revelation from Jesus Christ.

13 For you have heard of my previous way of life in Judaism, how intensely I persecuted the church of God and tried to destroy it. 14 I was advancing in Judaism beyond many of my own age among my people and was extremely zealous for the traditions of my fathers. 15 But when God, who set me apart from my mother’s womb and called me by his grace, was pleased 16 to reveal his Son in me so that I might preach him among the Gentiles, my immediate response was not to consult any human being. 17 I did not go up to Jerusalem to see those who were apostles before I was, but I went into Arabia. Later I returned to Damascus.

18 Then after three years, I went up to Jerusalem to get acquainted with Cephas[b] and stayed with him fifteen days. 19 I saw none of the other apostles—only James, the Lord’s brother. 20 I assure you before God that what I am writing you is no lie.

21 Then I went to Syria and Cilicia. 22 I was personally unknown to the churches of Judea that are in Christ. 23 They only heard the report: “The man who formerly persecuted us is now preaching the faith he once tried to destroy.” 24 And they praised God because of me.</p>
          </div>

          <div className={styles.card}>
              <h2  className={styles.chapter}>Galatians Chapter II</h2>
            <p>Paul Accepted by the Apostles
2 Then after fourteen years, I went up again to Jerusalem, this time with Barnabas. I took Titus along also. 2 I went in response to a revelation and, meeting privately with those esteemed as leaders, I presented to them the gospel that I preach among the Gentiles. I wanted to be sure I was not running and had not been running my race in vain. 3 Yet not even Titus, who was with me, was compelled to be circumcised, even though he was a Greek. 4 This matter arose because some false believers had infiltrated our ranks to spy on the freedom we have in Christ Jesus and to make us slaves. 5 We did not give in to them for a moment, so that the truth of the gospel might be preserved for you.

6 As for those who were held in high esteem—whatever they were makes no difference to me; God does not show favoritism—they added nothing to my message. 7 On the contrary, they recognized that I had been entrusted with the task of preaching the gospel to the uncircumcised,[a] just as Peter had been to the circumcised.[b] 8 For God, who was at work in Peter as an apostle to the circumcised, was also at work in me as an apostle to the Gentiles. 9 James, Cephas[c] and John, those esteemed as pillars, gave me and Barnabas the right hand of fellowship when they recognized the grace given to me. They agreed that we should go to the Gentiles, and they to the circumcised. 10 All they asked was that we should continue to remember the poor, the very thing I had been eager to do all along.

Paul Opposes Cephas
11 When Cephas came to Antioch, I opposed him to his face, because he stood condemned. 12 For before certain men came from James, he used to eat with the Gentiles. But when they arrived, he began to draw back and separate himself from the Gentiles because he was afraid of those who belonged to the circumcision group. 13 The other Jews joined him in his hypocrisy, so that by their hypocrisy even Barnabas was led astray.

14 When I saw that they were not acting in line with the truth of the gospel, I said to Cephas in front of them all, “You are a Jew, yet you live like a Gentile and not like a Jew. How is it, then, that you force Gentiles to follow Jewish customs?

15 “We who are Jews by birth and not sinful Gentiles 16 know that a person is not justified by the works of the law, but by faith in Jesus Christ. So we, too, have put our faith in Christ Jesus that we may be justified by faith in[d] Christ and not by the works of the law, because by the works of the law no one will be justified.

17 “But if, in seeking to be justified in Christ, we Jews find ourselves also among the sinners, doesn’t that mean that Christ promotes sin? Absolutely not! 18 If I rebuild what I destroyed, then I really would be a lawbreaker.

19 “For through the law I died to the law so that I might live for God. 20 I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me. 21 I do not set aside the grace of God, for if righteousness could be gained through the law, Christ died for nothing!”[e]

</p>
          </div>

          <div className={styles.card}
          >
             <h2  className={styles.chapter}>Chapter 3</h2>
            <p>Faith or Works of the Law
3 You foolish Galatians! Who has bewitched you? Before your very eyes Jesus Christ was clearly portrayed as crucified. 2 I would like to learn just one thing from you: Did you receive the Spirit by the works of the law, or by believing what you heard? 3 Are you so foolish? After beginning by means of the Spirit, are you now trying to finish by means of the flesh?[a] 4 Have you experienced[b] so much in vain—if it really was in vain? 5 So again I ask, does God give you his Spirit and work miracles among you by the works of the law, or by your believing what you heard? 6 So also Abraham “believed God, and it was credited to him as righteousness.”[c]

7 Understand, then, that those who have faith are children of Abraham. 8 Scripture foresaw that God would justify the Gentiles by faith, and announced the gospel in advance to Abraham: “All nations will be blessed through you.”[d] 9 So those who rely on faith are blessed along with Abraham, the man of faith.

10 For all who rely on the works of the law are under a curse, as it is written: “Cursed is everyone who does not continue to do everything written in the Book of the Law.”[e] 11 Clearly no one who relies on the law is justified before God, because “the righteous will live by faith.”[f] 12 The law is not based on faith; on the contrary, it says, “The person who does these things will live by them.”[g] 13 Christ redeemed us from the curse of the law by becoming a curse for us, for it is written: “Cursed is everyone who is hung on a pole.”[h] 14 He redeemed us in order that the blessing given to Abraham might come to the Gentiles through Christ Jesus, so that by faith we might receive the promise of the Spirit.

The Law and the Promise
15 Brothers and sisters, let me take an example from everyday life. Just as no one can set aside or add to a human covenant that has been duly established, so it is in this case. 16 The promises were spoken to Abraham and to his seed. Scripture does not say “and to seeds,” meaning many people, but “and to your seed,”[i] meaning one person, who is Christ. 17 What I mean is this: The law, introduced 430 years later, does not set aside the covenant previously established by God and thus do away with the promise. 18 For if the inheritance depends on the law, then it no longer depends on the promise; but God in his grace gave it to Abraham through a promise.

19 Why, then, was the law given at all? It was added because of transgressions until the Seed to whom the promise referred had come. The law was given through angels and entrusted to a mediator. 20 A mediator, however, implies more than one party; but God is one.

21 Is the law, therefore, opposed to the promises of God? Absolutely not! For if a law had been given that could impart life, then righteousness would certainly have come by the law. 22 But Scripture has locked up everything under the control of sin, so that what was promised, being given through faith in Jesus Christ, might be given to those who believe.

Children of God
23 Before the coming of this faith,[j] we were held in custody under the law, locked up until the faith that was to come would be revealed. 24 So the law was our guardian until Christ came that we might be justified by faith. 25 Now that this faith has come, we are no longer under a guardian.

26 So in Christ Jesus you are all children of God through faith, 27 for all of you who were baptized into Christ have clothed yourselves with Christ. 28 There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus. 29 If you belong to Christ, then you are Abraham’s seed, and heirs according to the promise.

</p>
          </div>

          <div
            className={styles.card}
          >
            <h2 className={styles.chapter}>Chapter 4</h2>
            <p>
            4 What I am saying is that as long as an heir is underage, he is no different from a slave, although he owns the whole estate. 2 The heir is subject to guardians and trustees until the time set by his father. 3 So also, when we were underage, we were in slavery under the elemental spiritual forces[a] of the world. 4 But when the set time had fully come, God sent his Son, born of a woman, born under the law, 5 to redeem those under the law, that we might receive adoption to sonship.[b] 6 Because you are his sons, God sent the Spirit of his Son into our hearts, the Spirit who calls out, “Abba,[c] Father.” 7 So you are no longer a slave, but God’s child; and since you are his child, God has made you also an heir.

Paul’s Concern for the Galatians
8 Formerly, when you did not know God, you were slaves to those who by nature are not gods. 9 But now that you know God—or rather are known by God—how is it that you are turning back to those weak and miserable forces[d]? Do you wish to be enslaved by them all over again? 10 You are observing special days and months and seasons and years! 11 I fear for you, that somehow I have wasted my efforts on you.

12 I plead with you, brothers and sisters, become like me, for I became like you. You did me no wrong. 13 As you know, it was because of an illness that I first preached the gospel to you, 14 and even though my illness was a trial to you, you did not treat me with contempt or scorn. Instead, you welcomed me as if I were an angel of God, as if I were Christ Jesus himself. 15 Where, then, is your blessing of me now? I can testify that, if you could have done so, you would have torn out your eyes and given them to me. 16 Have I now become your enemy by telling you the truth?

17 Those people are zealous to win you over, but for no good. What they want is to alienate you from us, so that you may have zeal for them. 18 It is fine to be zealous, provided the purpose is good, and to be so always, not just when I am with you. 19 My dear children, for whom I am again in the pains of childbirth until Christ is formed in you, 20 how I wish I could be with you now and change my tone, because I am perplexed about you!

Hagar and Sarah
21 Tell me, you who want to be under the law, are you not aware of what the law says? 22 For it is written that Abraham had two sons, one by the slave woman and the other by the free woman. 23 His son by the slave woman was born according to the flesh, but his son by the free woman was born as the result of a divine promise.

24 These things are being taken figuratively: The women represent two covenants. One covenant is from Mount Sinai and bears children who are to be slaves: This is Hagar. 25 Now Hagar stands for Mount Sinai in Arabia and corresponds to the present city of Jerusalem, because she is in slavery with her children. 26 But the Jerusalem that is above is free, and she is our mother. 27 For it is written:

“Be glad, barren woman,
    you who never bore a child;
shout for joy and cry aloud,
    you who were never in labor;
because more are the children of the desolate woman
    than of her who has a husband.”[e]

28 Now you, brothers and sisters, like Isaac, are children of promise. 29 At that time the son born according to the flesh persecuted the son born by the power of the Spirit. It is the same now. 30 But what does Scripture say? “Get rid of the slave woman and her son, for the slave woman’s son will never share in the inheritance with the free woman’s son.”[f] 31 Therefore, brothers and sisters, we are not children of the slave woman, but of the free woman.
            </p>
          </div>

          <div
            className={styles.card}
          >
             <h2  className={styles.chapter}>Chapter 5</h2>
            <p>
            Freedom in Christ
5 It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.

2 Mark my words! I, Paul, tell you that if you let yourselves be circumcised, Christ will be of no value to you at all. 3 Again I declare to every man who lets himself be circumcised that he is obligated to obey the whole law. 4 You who are trying to be justified by the law have been alienated from Christ; you have fallen away from grace. 5 For through the Spirit we eagerly await by faith the righteousness for which we hope. 6 For in Christ Jesus neither circumcision nor uncircumcision has any value. The only thing that counts is faith expressing itself through love.

7 You were running a good race. Who cut in on you to keep you from obeying the truth? 8 That kind of persuasion does not come from the one who calls you. 9 “A little yeast works through the whole batch of dough.” 10 I am confident in the Lord that you will take no other view. The one who is throwing you into confusion, whoever that may be, will have to pay the penalty. 11 Brothers and sisters, if I am still preaching circumcision, why am I still being persecuted? In that case the offense of the cross has been abolished. 12 As for those agitators, I wish they would go the whole way and emasculate themselves!

Life by the Spirit
13 You, my brothers and sisters, were called to be free. But do not use your freedom to indulge the flesh[a]; rather, serve one another humbly in love. 14 For the entire law is fulfilled in keeping this one command: “Love your neighbor as yourself.”[b] 15 If you bite and devour each other, watch out or you will be destroyed by each other.

16 So I say, walk by the Spirit, and you will not gratify the desires of the flesh. 17 For the flesh desires what is contrary to the Spirit, and the Spirit what is contrary to the flesh. They are in conflict with each other, so that you are not to do whatever[c] you want. 18 But if you are led by the Spirit, you are not under the law.

19 The acts of the flesh are obvious: sexual immorality, impurity and debauchery; 20 idolatry and witchcraft; hatred, discord, jealousy, fits of rage, selfish ambition, dissensions, factions 21 and envy; drunkenness, orgies, and the like. I warn you, as I did before, that those who live like this will not inherit the kingdom of God.

22 But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, 23 gentleness and self-control. Against such things there is no law. 24 Those who belong to Christ Jesus have crucified the flesh with its passions and desires. 25 Since we live by the Spirit, let us keep in step with the Spirit. 26 Let us not become conceited, provoking and envying each other.


            </p>
          </div>

          <div
            className={styles.card}
          >
             <h2 className={styles.chapter}>Chapter 6</h2>
            <p>
            Doing Good to All
6 Brothers and sisters, if someone is caught in a sin, you who live by the Spirit should restore that person gently. But watch yourselves, or you also may be tempted. 2 Carry each other’s burdens, and in this way you will fulfill the law of Christ. 3 If anyone thinks they are something when they are not, they deceive themselves. 4 Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else, 5 for each one should carry their own load. 6 Nevertheless, the one who receives instruction in the word should share all good things with their instructor.

7 Do not be deceived: God cannot be mocked. A man reaps what he sows. 8 Whoever sows to please their flesh, from the flesh will reap destruction; whoever sows to please the Spirit, from the Spirit will reap eternal life. 9 Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. 10 Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.

Not Circumcision but the New Creation
11 See what large letters I use as I write to you with my own hand!

12 Those who want to impress people by means of the flesh are trying to compel you to be circumcised. The only reason they do this is to avoid being persecuted for the cross of Christ. 13 Not even those who are circumcised keep the law, yet they want you to be circumcised that they may boast about your circumcision in the flesh. 14 May I never boast except in the cross of our Lord Jesus Christ, through which[a] the world has been crucified to me, and I to the world. 15 Neither circumcision nor uncircumcision means anything; what counts is the new creation. 16 Peace and mercy to all who follow this rule—to[b] the Israel of God.

17 From now on, let no one cause me trouble, for I bear on my body the marks of Jesus.

18 The grace of our Lord Jesus Christ be with your spirit, brothers and sisters. Amen.
            </p>
          </div>


        </div>
</div>
      </main>
  
<main id="first_peter" className={styles.main}>
       
        <div id="first_thessalonians" className={styles.hero}>
                <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-word-of-god.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        <h1 className={styles.title}>
       I PETER
        </h1>
          <div className={styles.iframe1}>
                        <iframe width="100%" height="300" src="https://www.youtube.com/embed/KgVLE_JVhBs?si=sxT5iNn5zeNtu2GT&autoplay=1&mute=1" title="YouTube video player" frameborder="10" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                          
                        </div>
    <p className={styles.parables}>

         Urges Christians in Asia minor, remember how Jesus suffered for them, & trust Him to care for them.
</p>                                                      
                  <div className={styles.nav2}>           
      <a href="https://romans-five.vercel.app/#james">
                                                      <p>Prev</p>
             <Image 
                                src="/previous.webp"
                                alt="prev"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>

        
      <a href="https://cash.app/$JNutt367">
                                  <p>Give</p>
              <Image className={styles.arrow}
                                src="/donations_please.webp"
                                alt="donations_please.webp"
                                height={25}
                                width={25}
                                priority
                              /> 
       </a>
         <a href="https://galatians.vercel.app/#second_peter">
                                  <p>Next</p>
           <Image 
                                src="/next.webp"
                                alt="next"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         
               </div>
               <div className={styles.iframe}> 
<iframe width="100%" height="315" src="https://www.youtube.com/embed/WhP7AZQlzCg?autoplay=1&mute=1" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>                       
                                  </div>
                                  
                              
        <div className={styles.grid2}>
          <div className={styles.card2}>
           <h2  className={styles.chapter2}>I Peter Chapter I</h2>
            <p> 
                                                                        1 Peter, an apostle of Jesus Christ,
                                                
                                                To God’s elect, exiles scattered throughout the provinces of Pontus, Galatia, Cappadocia, Asia and Bithynia, 2 who have been chosen according to the foreknowledge of God the Father, through the sanctifying work of the Spirit, to be obedient to Jesus Christ and sprinkled with his blood:
                                                
                                                Grace and peace be yours in abundance.
                                                
                                                Praise to God for a Living Hope
                                                3 Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead, 4 and into an inheritance that can never perish, spoil or fade. This inheritance is kept in heaven for you, 5 who through faith are shielded by God’s power until the coming of the salvation that is ready to be revealed in the last time. 6 In all this you greatly rejoice, though now for a little while you may have had to suffer grief in all kinds of trials. 7 These have come so that the proven genuineness of your faith—of greater worth than gold, which perishes even though refined by fire—may result in praise, glory and honor when Jesus Christ is revealed. 8 Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy, 9 for you are receiving the end result of your faith, the salvation of your souls.
                                                
                                                10 Concerning this salvation, the prophets, who spoke of the grace that was to come to you, searched intently and with the greatest care, 11 trying to find out the time and circumstances to which the Spirit of Christ in them was pointing when he predicted the sufferings of the Messiah and the glories that would follow. 12 It was revealed to them that they were not serving themselves but you, when they spoke of the things that have now been told you by those who have preached the gospel to you by the Holy Spirit sent from heaven. Even angels long to look into these things.
                                                
                                                Be Holy
                                                13 Therefore, with minds that are alert and fully sober, set your hope on the grace to be brought to you when Jesus Christ is revealed at his coming. 14 As obedient children, do not conform to the evil desires you had when you lived in ignorance. 15 But just as he who called you is holy, so be holy in all you do; 16 for it is written: “Be holy, because I am holy.”[a]
                                                
                                                17 Since you call on a Father who judges each person’s work impartially, live out your time as foreigners here in reverent fear. 18 For you know that it was not with perishable things such as silver or gold that you were redeemed from the empty way of life handed down to you from your ancestors, 19 but with the precious blood of Christ, a lamb without blemish or defect. 20 He was chosen before the creation of the world, but was revealed in these last times for your sake. 21 Through him you believe in God, who raised him from the dead and glorified him, and so your faith and hope are in God.
                                                
                                                22 Now that you have purified yourselves by obeying the truth so that you have sincere love for each other, love one another deeply, from the heart.[b] 23 For you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God. 24 For,
                                                
                                                “All people are like grass,
                                                    and all their glory is like the flowers of the field;
                                                the grass withers and the flowers fall,
                                                25     but the word of the Lord endures forever.”[c]
                                                
                                                And this is the word that was preached to you.


  </p>
          </div>

          <div className={styles.card2}>
            <h2 className={styles.chapter2}>I Peter Chapter II</h2>
            <p> 
                                                                                   2 Therefore, rid yourselves of all malice and all deceit, hypocrisy, envy, and slander of every kind. 2 Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation, 3 now that you have tasted that the Lord is good.
                                                                
                                                                The Living Stone and a Chosen People
                                                                4 As you come to him, the living Stone—rejected by humans but chosen by God and precious to him— 5 you also, like living stones, are being built into a spiritual house[a] to be a holy priesthood, offering spiritual sacrifices acceptable to God through Jesus Christ. 6 For in Scripture it says:
                                                                
                                                                “See, I lay a stone in Zion,
                                                                    a chosen and precious cornerstone,
                                                                and the one who trusts in him
                                                                    will never be put to shame.”[b]
                                                                
                                                                7 Now to you who believe, this stone is precious. But to those who do not believe,
                                                                
                                                                “The stone the builders rejected
                                                                    has become the cornerstone,”[c]
                                                                
                                                                8 and,
                                                                
                                                                “A stone that causes people to stumble
                                                                    and a rock that makes them fall.”[d]
                                                                
                                                                They stumble because they disobey the message—which is also what they were destined for.
                                                                
                                                                9 But you are a chosen people, a royal priesthood, a holy nation, God’s special possession, that you may declare the praises of him who called you out of darkness into his wonderful light. 10 Once you were not a people, but now you are the people of God; once you had not received mercy, but now you have received mercy.
                                                                
                                                                Living Godly Lives in a Pagan Society
                                                                11 Dear friends, I urge you, as foreigners and exiles, to abstain from sinful desires, which wage war against your soul. 12 Live such good lives among the pagans that, though they accuse you of doing wrong, they may see your good deeds and glorify God on the day he visits us.
                                                                
                                                                13 Submit yourselves for the Lord’s sake to every human authority: whether to the emperor, as the supreme authority, 14 or to governors, who are sent by him to punish those who do wrong and to commend those who do right. 15 For it is God’s will that by doing good you should silence the ignorant talk of foolish people. 16 Live as free people, but do not use your freedom as a cover-up for evil; live as God’s slaves. 17 Show proper respect to everyone, love the family of believers, fear God, honor the emperor.
                                                                
                                                                18 Slaves, in reverent fear of God submit yourselves to your masters, not only to those who are good and considerate, but also to those who are harsh. 19 For it is commendable if someone bears up under the pain of unjust suffering because they are conscious of God. 20 But how is it to your credit if you receive a beating for doing wrong and endure it? But if you suffer for doing good and you endure it, this is commendable before God. 21 To this you were called, because Christ suffered for you, leaving you an example, that you should follow in his steps.
                                                                
                                                                22 “He committed no sin,
                                                                    and no deceit was found in his mouth.”[e]
                                                                
                                                                23 When they hurled their insults at him, he did not retaliate; when he suffered, he made no threats. Instead, he entrusted himself to him who judges justly. 24 “He himself bore our sins” in his body on the cross, so that we might die to sins and live for righteousness; “by his wounds you have been healed.” 25 For “you were like sheep going astray,”[f] but now you have returned to the Shepherd and Overseer of your souls.
  </p>
          </div>

          <div
            className={styles.card2}
          >
            <h2 className={styles.chapter2}>I Peter Chapter III </h2>
                    <p>
                                                                              3 Wives, in the same way submit yourselves to your own husbands so that, if any of them do not believe the word, they may be won over without words by the behavior of their wives, 2 when they see the purity and reverence of your lives. 3 Your beauty should not come from outward adornment, such as elaborate hairstyles and the wearing of gold jewelry or fine clothes. 4 Rather, it should be that of your inner self, the unfading beauty of a gentle and quiet spirit, which is of great worth in God’s sight. 5 For this is the way the holy women of the past who put their hope in God used to adorn themselves. They submitted themselves to their own husbands, 6 like Sarah, who obeyed Abraham and called him her lord. You are her daughters if you do what is right and do not give way to fear.
                                                      
                                                      7 Husbands, in the same way be considerate as you live with your wives, and treat them with respect as the weaker partner and as heirs with you of the gracious gift of life, so that nothing will hinder your prayers.
                                                      
                                                      Suffering for Doing Good
                                                      8 Finally, all of you, be like-minded, be sympathetic, love one another, be compassionate and humble. 9 Do not repay evil with evil or insult with insult. On the contrary, repay evil with blessing, because to this you were called so that you may inherit a blessing. 10 For,
                                                      
                                                      “Whoever would love life
                                                          and see good days
                                                      must keep their tongue from evil
                                                          and their lips from deceitful speech.
                                                      11 They must turn from evil and do good;
                                                          they must seek peace and pursue it.
                                                      12 For the eyes of the Lord are on the righteous
                                                          and his ears are attentive to their prayer,
                                                      but the face of the Lord is against those who do evil.”[a]
                                                      
                                                      13 Who is going to harm you if you are eager to do good? 14 But even if you should suffer for what is right, you are blessed. “Do not fear their threats[b]; do not be frightened.”[c] 15 But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have. But do this with gentleness and respect, 16 keeping a clear conscience, so that those who speak maliciously against your good behavior in Christ may be ashamed of their slander. 17 For it is better, if it is God’s will, to suffer for doing good than for doing evil. 18 For Christ also suffered once for sins, the righteous for the unrighteous, to bring you to God. He was put to death in the body but made alive in the Spirit. 19 After being made alive,[d] he went and made proclamation to the imprisoned spirits— 20 to those who were disobedient long ago when God waited patiently in the days of Noah while the ark was being built. In it only a few people, eight in all, were saved through water, 21 and this water symbolizes baptism that now saves you also—not the removal of dirt from the body but the pledge of a clear conscience toward God.[e] It saves you by the resurrection of Jesus Christ, 22 who has gone into heaven and is at God’s right hand—with angels, authorities and powers in submission to him.
  </p>
          </div>

          <div className={styles.card2}
          >
            <h2 className={styles.chapter2}>I Peter Chapter IV </h2>
            <p>
                                                                              Living for God
                                                        4 Therefore, since Christ suffered in his body, arm yourselves also with the same attitude, because whoever suffers in the body is done with sin. 2 As a result, they do not live the rest of their earthly lives for evil human desires, but rather for the will of God. 3 For you have spent enough time in the past doing what pagans choose to do—living in debauchery, lust, drunkenness, orgies, carousing and detestable idolatry. 4 They are surprised that you do not join them in their reckless, wild living, and they heap abuse on you. 5 But they will have to give account to him who is ready to judge the living and the dead. 6 For this is the reason the gospel was preached even to those who are now dead, so that they might be judged according to human standards in regard to the body, but live according to God in regard to the spirit.
                                                        
                                                        7 The end of all things is near. Therefore be alert and of sober mind so that you may pray. 8 Above all, love each other deeply, because love covers over a multitude of sins. 9 Offer hospitality to one another without grumbling. 10 Each of you should use whatever gift you have received to serve others, as faithful stewards of God’s grace in its various forms. 11 If anyone speaks, they should do so as one who speaks the very words of God. If anyone serves, they should do so with the strength God provides, so that in all things God may be praised through Jesus Christ. To him be the glory and the power for ever and ever. Amen.
                                                        
                                                        Suffering for Being a Christian
                                                        12 Dear friends, do not be surprised at the fiery ordeal that has come on you to test you, as though something strange were happening to you. 13 But rejoice inasmuch as you participate in the sufferings of Christ, so that you may be overjoyed when his glory is revealed. 14 If you are insulted because of the name of Christ, you are blessed, for the Spirit of glory and of God rests on you. 15 If you suffer, it should not be as a murderer or thief or any other kind of criminal, or even as a meddler. 16 However, if you suffer as a Christian, do not be ashamed, but praise God that you bear that name. 17 For it is time for judgment to begin with God’s household; and if it begins with us, what will the outcome be for those who do not obey the gospel of God? 18 And,
                                                        
                                                        “If it is hard for the righteous to be saved,
                                                            what will become of the ungodly and the sinner?”[a]
                                                        
                                                        19 So then, those who suffer according to God’s will should commit themselves to their faithful Creator and continue to do good.

            </p>
          </div>
          <div className={styles.card2}
          >
            <h2 className={styles.chapter2}>I Peter Chapter V</h2>
                              <p> 
                                                                                                  To the Elders and the Flock
                                                        5 To the elders among you, I appeal as a fellow elder and a witness of Christ’s sufferings who also will share in the glory to be revealed: 2 Be shepherds of God’s flock that is under your care, watching over them—not because you must, but because you are willing, as God wants you to be; not pursuing dishonest gain, but eager to serve; 3 not lording it over those entrusted to you, but being examples to the flock. 4 And when the Chief Shepherd appears, you will receive the crown of glory that will never fade away.
                                                        
                                                        5 In the same way, you who are younger, submit yourselves to your elders. All of you, clothe yourselves with humility toward one another, because,
                                                        
                                                        “God opposes the proud
                                                            but shows favor to the humble.”[a]
                                                        
                                                        6 Humble yourselves, therefore, under God’s mighty hand, that he may lift you up in due time. 7 Cast all your anxiety on him because he cares for you.
                                                        
                                                        8 Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour. 9 Resist him, standing firm in the faith, because you know that the family of believers throughout the world is undergoing the same kind of sufferings.
                                                        
                                                        10 And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong, firm and steadfast. 11 To him be the power for ever and ever. Amen.
                                                        
                                                        Final Greetings
                                                        12 With the help of Silas,[b] whom I regard as a faithful brother, I have written to you briefly, encouraging you and testifying that this is the true grace of God. Stand fast in it.
                                                        
                                                        13 She who is in Babylon, chosen together with you, sends you her greetings, and so does my son Mark. 14 Greet one another with a kiss of love.
                                                        
                                                        Peace to all of you who are in Christ.
  
  </p>
          </div>

   
          <div className={styles.card2}
          >
            <h2 className={styles.chapter2}>!Explaination of Layout!</h2>
            <p>
            I have appended 1 Thessalonians to the bottom of 1 corinthians...
            I have appended 2 Thessalonians to the bottom of 2 corinthians...
            I have appended 1 Timothy to the bottom of the gospel of Matthew...
            I have appended 2 Timothy to the bottom of the gospel of Mark...
            I have appended Titus to the bottom of the gospel of Luke...
            I have appended Philemon to the bottom of the gospel of John...
            I have appended Hebrews to the bottom of the book of Acts ...
            I have appended James to the bottom of Romans ...
            I have appended I Peter to the bottom of Galatians
            I will be appending II Peter ...TBA
            I will be appending I John ...TBA
            I will be appending II John ...TBA
            I will be appending III John ...TBA
            I will be appending Jude ...TBA
                        More to come on the layout...!
     </p>
          </div>


     

        </div>
</div>
        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>
      </main>



<main id="second_peter" className={styles.main}>
       
        <div id="first_thessalonians" className={styles.hero}>
                <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-word-of-god.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        <h1 className={styles.title}>
       II PETER
        </h1>
          <div className={styles.iframe1}>
                          <iframe width="100%" height="300" src="https://www.youtube.com/embed/KgVLE_JVhBs?si=sxT5iNn5zeNtu2GT&autoplay=1&mute=1" title="YouTube video player" frameborder="10" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

                        </div>
    <p className={styles.parables}>

         Reminds Christians the best resistance to false teachings, to grow in the knowledge of our Lord & Savior.
</p>                                                      
                  <div className={styles.nav2}>           
      <a href="https://romans-five.vercel.app/#james">
                          <p>Prev</p>
             <Image 
                                src="/previous.webp"
                                alt="prev"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>

        
      <a href="https://cash.app/$JNutt367">

                                  <p>Give</p>
              <Image className={styles.arrow}
                                src="/donations_please.webp"
                                alt="donations_please.webp"
                                height={25}
                                width={25}
                                priority
                              /> 
       </a>
         <a href="https://first-thessalonians.vercel.app/">

                                  <p>Next</p>
           <Image 
                                src="/next.webp"
                                alt="next"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         
               </div>
               <div className={styles.iframe}> 
<iframe width="100%" height="315" src="https://www.youtube.com/embed/wWLv_ITyKYc?autoplay=1&mute=1" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>                      
                                  </div>
                                  
                              
        <div className={styles.grid2}>
                      <div className={styles.card2}>
                       <h2  className={styles.chapter2}>II Peter Chapter I</h2>
                        <p> 
                                                                                                         1 Simon Peter, a servant and apostle of Jesus Christ,
                                            
                                            To those who through the righteousness of our God and Savior Jesus Christ have received a faith as precious as ours:
                                            
                                            2 Grace and peace be yours in abundance through the knowledge of God and of Jesus our Lord.
                                            
                                            Confirming One’s Calling and Election
                                            3 His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness. 4 Through these he has given us his very great and precious promises, so that through them you may participate in the divine nature, having escaped the corruption in the world caused by evil desires.
                                            
                                            5 For this very reason, make every effort to add to your faith goodness; and to goodness, knowledge; 6 and to knowledge, self-control; and to self-control, perseverance; and to perseverance, godliness; 7 and to godliness, mutual affection; and to mutual affection, love. 8 For if you possess these qualities in increasing measure, they will keep you from being ineffective and unproductive in your knowledge of our Lord Jesus Christ. 9 But whoever does not have them is nearsighted and blind, forgetting that they have been cleansed from their past sins.
                                            
                                            10 Therefore, my brothers and sisters,[a] make every effort to confirm your calling and election. For if you do these things, you will never stumble, 11 and you will receive a rich welcome into the eternal kingdom of our Lord and Savior Jesus Christ.
                                            
                                            Prophecy of Scripture
                                            12 So I will always remind you of these things, even though you know them and are firmly established in the truth you now have. 13 I think it is right to refresh your memory as long as I live in the tent of this body, 14 because I know that I will soon put it aside, as our Lord Jesus Christ has made clear to me. 15 And I will make every effort to see that after my departure you will always be able to remember these things.
                                            
                                            16 For we did not follow cleverly devised stories when we told you about the coming of our Lord Jesus Christ in power, but we were eyewitnesses of his majesty. 17 He received honor and glory from God the Father when the voice came to him from the Majestic Glory, saying, “This is my Son, whom I love; with him I am well pleased.”[b] 18 We ourselves heard this voice that came from heaven when we were with him on the sacred mountain.
                                            
                                            19 We also have the prophetic message as something completely reliable, and you will do well to pay attention to it, as to a light shining in a dark place, until the day dawns and the morning star rises in your hearts. 20 Above all, you must understand that no prophecy of Scripture came about by the prophet’s own interpretation of things. 21 For prophecy never had its origin in the human will, but prophets, though human, spoke from God as they were carried along by the Holy Spirit.


                          </p>
                                  </div>

                <div className={styles.card2}>
                  <h2 className={styles.chapter2}>II Peter Chapter II</h2>
                  <p> 

                                    False Teachers and Their Destruction
                                    2 But there were also false prophets among the people, just as there will be false teachers among you. They will secretly introduce destructive heresies, even denying the sovereign Lord who bought them—bringing swift destruction on themselves. 2 Many will follow their depraved conduct and will bring the way of truth into disrepute. 3 In their greed these teachers will exploit you with fabricated stories. Their condemnation has long been hanging over them, and their destruction has not been sleeping.
                                    
                                    4 For if God did not spare angels when they sinned, but sent them to hell,[a] putting them in chains of darkness[b] to be held for judgment; 5 if he did not spare the ancient world when he brought the flood on its ungodly people, but protected Noah, a preacher of righteousness, and seven others; 6 if he condemned the cities of Sodom and Gomorrah by burning them to ashes, and made them an example of what is going to happen to the ungodly; 7 and if he rescued Lot, a righteous man, who was distressed by the depraved conduct of the lawless 8 (for that righteous man, living among them day after day, was tormented in his righteous soul by the lawless deeds he saw and heard)— 9 if this is so, then the Lord knows how to rescue the godly from trials and to hold the unrighteous for punishment on the day of judgment. 10 This is especially true of those who follow the corrupt desire of the flesh[c] and despise authority.
                                    
                                    Bold and arrogant, they are not afraid to heap abuse on celestial beings; 11 yet even angels, although they are stronger and more powerful, do not heap abuse on such beings when bringing judgment on them from[d] the Lord. 12 But these people blaspheme in matters they do not understand. They are like unreasoning animals, creatures of instinct, born only to be caught and destroyed, and like animals they too will perish.
                                    
                                    13 They will be paid back with harm for the harm they have done. Their idea of pleasure is to carouse in broad daylight. They are blots and blemishes, reveling in their pleasures while they feast with you.[e] 14 With eyes full of adultery, they never stop sinning; they seduce the unstable; they are experts in greed—an accursed brood! 15 They have left the straight way and wandered off to follow the way of Balaam son of Bezer,[f] who loved the wages of wickedness. 16 But he was rebuked for his wrongdoing by a donkey—an animal without speech—who spoke with a human voice and restrained the prophet’s madness.
                                    
                                    17 These people are springs without water and mists driven by a storm. Blackest darkness is reserved for them. 18 For they mouth empty, boastful words and, by appealing to the lustful desires of the flesh, they entice people who are just escaping from those who live in error. 19 They promise them freedom, while they themselves are slaves of depravity—for “people are slaves to whatever has mastered them.” 20 If they have escaped the corruption of the world by knowing our Lord and Savior Jesus Christ and are again entangled in it and are overcome, they are worse off at the end than they were at the beginning. 21 It would have been better for them not to have known the way of righteousness, than to have known it and then to turn their backs on the sacred command that was passed on to them. 22 Of them the proverbs are true: “A dog returns to its vomit,”[g] and, “A sow that is washed returns to her wallowing in the mud.”


                        </p>
                      </div>

                              <div
                                className={styles.card2}
                              >
                                <h2 className={styles.chapter2}>II Peter Chapter III </h2>
                    <p>
                                                                                                                  The Day of the Lord
                                            3 Dear friends, this is now my second letter to you. I have written both of them as reminders to stimulate you to wholesome thinking. 2 I want you to recall the words spoken in the past by the holy prophets and the command given by our Lord and Savior through your apostles.
                                            
                                            3 Above all, you must understand that in the last days scoffers will come, scoffing and following their own evil desires. 4 They will say, “Where is this ‘coming’ he promised? Ever since our ancestors died, everything goes on as it has since the beginning of creation.” 5 But they deliberately forget that long ago by God’s word the heavens came into being and the earth was formed out of water and by water. 6 By these waters also the world of that time was deluged and destroyed. 7 By the same word the present heavens and earth are reserved for fire, being kept for the day of judgment and destruction of the ungodly.
                                            
                                            8 But do not forget this one thing, dear friends: With the Lord a day is like a thousand years, and a thousand years are like a day. 9 The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance.
                                            
                                            10 But the day of the Lord will come like a thief. The heavens will disappear with a roar; the elements will be destroyed by fire, and the earth and everything done in it will be laid bare.[a]
                                            
                                            11 Since everything will be destroyed in this way, what kind of people ought you to be? You ought to live holy and godly lives 12 as you look forward to the day of God and speed its coming.[b] That day will bring about the destruction of the heavens by fire, and the elements will melt in the heat. 13 But in keeping with his promise we are looking forward to a new heaven and a new earth, where righteousness dwells.
                                            
                                            14 So then, dear friends, since you are looking forward to this, make every effort to be found spotless, blameless and at peace with him. 15 Bear in mind that our Lord’s patience means salvation, just as our dear brother Paul also wrote you with the wisdom that God gave him. 16 He writes the same way in all his letters, speaking in them of these matters. His letters contain some things that are hard to understand, which ignorant and unstable people distort, as they do the other Scriptures, to their own destruction.
                                            
                                            17 Therefore, dear friends, since you have been forewarned, be on your guard so that you may not be carried away by the error of the lawless and fall from your secure position. 18 But grow in the grace and knowledge of our Lord and Savior Jesus Christ. To him be glory both now and forever! Amen.
                                              
                  </p>
                          </div>

       
   
          <div className={styles.card2}
          >
            <h2 className={styles.chapter2}>!Explaination of Layout!</h2>
            <p>
            I have appended 1 Thessalonians to the bottom of 1 corinthians...
            I have appended 2 Thessalonians to the bottom of 2 corinthians...
            I have appended 1 Timothy to the bottom of the gospel of Matthew...
            I have appended 2 Timothy to the bottom of the gospel of Mark...
            I have appended Titus to the bottom of the gospel of Luke...
            I have appended Philemon to the bottom of the gospel of John...
            I have appended Hebrews to the bottom of the book of Acts ...
            I have appended James to the bottom of Romans ...
            I have appended I Peter to the bottom of Galatians ...
            I have appended II Peter to the bottom of I Peter ... 
            I will be appending I John ...TBA
            I will be appending II John ...TBA
            I will be appending III John ...TBA
            I will be appending Jude ...TBA
                        More to come on the layout...!
     </p>
          </div>


     

        </div>
</div>
        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>
      </main>















                          
    </div>
  )
}
